### ISSUE TITLE
Fix login form responsiveness

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LucileDT/boustigraille#116]
The login form in mobile devices is hard to use because of the bad layout (see screenshot below).

![image](https://user-images.githubusercontent.com/50443097/156934215-a0bddcc4-266b-402e-954a-902591496b58.png)

### Todo

- [x] Make it responsive
  - [x] Remove left and right margin
  - [x] Make the input fields be screen wide
  - [x] Make the submit button be screen wide
