### ISSUE TITLE
Make recipes usable as ingredient in other recipes

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LucileDT/boustigraille#139]
We need to be able to create new recipes that are composed of other recipes.

For example if we make home-made tomato sauce we might want to add it to the pasta alla bolognese recipe.

### Todo

- [ ] Create an `ingredientable` trait
- [ ] Implement it in for the ingredient class
- [ ] Implement it in for the recipe class
- [ ] Update the relationship in recipe to take an `ingredientable` entity
  - Use polymorphism for this
- [ ] Update the recipe CRUD for it to use the new relationship  
  - [ ] CREATE
  - [ ] READ
  - [ ] UPDATE
